version: '3.7'

services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      DB_NAME: "postgres"
      DB_HOST: "localhost"
      POSTGRES_PASSWORD: "postgres"
      USER_NAME: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
